mail-wrapper: Update ax-common boilerplate code
Now "ax-common.sh" is correctly found in a local user's home directory.

diff --git a/mail/wrapper/mail-wrapper b/mail/wrapper/mail-wrapper
--- a/mail/wrapper/mail-wrapper
+++ b/mail/wrapper/mail-wrapper
@@ -13,14 +13,14 @@ NAME=$(basename "$0")
 
 # Include "ax-common.sh":
 ax_common_sourced=
-for dir in "$HOME/lib" "$HOME/.ax" /usr/local /opt/ax /usr; do
+for dir in "$HOME" "$HOME/.ax" /usr/local /opt/ax /usr; do
 	[ -z "$ax_common_sourced" ] || break
 	ax_common="${dir}/lib/ax/ax-common.sh"
 	# shellcheck source=/usr/local/lib/ax/ax-common.sh
 	[ -r "$ax_common" ] && . "$ax_common"
 done
 if [ -z "$ax_common_sourced" ]; then
-	echo "Error ($NAME): \"ax-common.sh\" not found, aborting!" >&2
+	echo "Error ($(basename "$0")): \"ax-common.sh\" not found, aborting!" >&2
 	echo "Please install 'ax-unix', \"Alex' UNIX Tools & Scripts\", and try again."
 	exit 99
 fi
